apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: java-app-ingress
  labels:
    app: java-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: java-app-svc
            port:
              number: 8080
  tls:
  - hosts:
    - mmsassignment.com
    secretName: java-app-ingress-tls
