apiVersion: v1
kind: Pod
metadata:
  labels:
    app: java-app
    run: java-app
  name: java-app
spec:
  containers:
  - image: khayalghosh/java-app:{{ .Values.image.tag }}
    name: java-app
    resources: {}
    volumeMounts:
      - name: log
        mountPath: /var/log
  volumes:
  - name: log
    persistentVolumeClaim:
      claimName: myapp-log-pvc
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
