apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: java-app
  name: java-app-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: java-app
    run: java-app
  type: ClusterIP
status:
  loadBalancer: {}
